### PR TITLE
Fixing #6 and making the build paths configurable

### LINKED ISSUE #6: no saves on steam version (Jul-2020 65786)
Using the latest file from Nexus the game loads just fine but no autosaves are happening.

**game version**

- Steam Jul-2020 65786

**mod version**

- 1.3.5 (?)
- https://www.nexusmods.com/subnautica/mods/237?tab=files&file_id=2091
- v1.3.5-237-1-3-5-1583061282.zip

I'm not familiar with the logs enough to spot any errors.

### PR DESCRIPTION
**Pull request by Bisa**
This PR will:
- update the build process (else I'm unable to build locally)
- update GetSavePath() for Steam, fixes #6
- update the AutosaveCoroutine to check for missing SaveGame directory (and abort if that's the case)

The included .dll was built using `dotnet msbuild -p:Platform=AnyCPU -p:Configuration=Release`

### CODE REVIEW

**Comment by DingoDjango** [comment]
I assume this is the tested & working version. Nice work. I just have a few extra nitpicks -
1) Was this built using the latest QMods release?
2) Didn't mod.json get a few changes with recent QMods revisions? Or is it just fine as is?
3) It would be better to use the Translate framework and add the new error messages to the English language file. That makes updating / translating everything easier for everyone.

**Comment by Bisa** [comment]
1. Built with QMods 4.0.2.2 (idea for a TODO to have this information added during build)
2. Hmm, it's working fine as it is right now and no changes were made by me to the mod.json
3. (I saw you removed this one) But yes it would be better to use the Translate()! :) I added the TODOs where I cheated and hardcoded strings to allow me to return to this later

**Comment by Bisa** [comment]
@DingoDjango - regarding the mod.json I had a look at https://github.com/SubnauticaModding/QModManager/wiki/Creating-your-mod.json-file and the file here follows that format.

However!
I did not update the version number in it, I'd prefer to leave that up to you but seeing as you might still be out of reach of your PC(?) I could update both the mod.json and the AssemblyInfo.cs with a version of your choosing and push to this PR?

**Comment by Bisa** [comment]
And while checking the AssemblyInfo.cs I also notice that you claim copyright to the assembly itself within that.
Just for the record, If I build the .dll I'm perfectly fine with allowing you that claim.

**Comment by DingoDjango** [comment]
The mod is MIT licensed so the assembly credit means next to nothing, really. As for the version I guess this would be v1.4.0

**Comment by Bisa** [comment]
There's a 1.4.0.0 for you :)

Yea, you are correct, MIT does that for the source - but the copyright claim is put on the on the .dll file itself suggesting that one needs to check with you if they want to modify the .dll file.
I know, not that important due to the MIT for the source, but if we want to be picky the assembly info should probably point out that it's MIT and refer to the source code for contributors if you want to allow others to play around with the .dll

All I'm saying is Im fine with giving you the copyright for the .dll here but if you intended something else by using the MIT lic you might want to adjust that :)

**Comment by DingoDjango** [comment]
> There's a 1.4.0.0 for you :)
> 
> Yea, you are correct, MIT does that for the source - but the copyright claim is put on the on the .dll file itself suggesting that one needs to check with you if they want to modify the .dll file.
> I know, not that important due to the MIT for the source, but if we want to be picky the assembly info should probably point out that it's MIT and refer to the source code for contributors if you want to allow others to play around with the .dll
> 
> All I'm saying is Im fine with giving you the copyright for the .dll here but if you intended something else by using the MIT lic you might want to adjust that :)

OK. Updated and credited. Thank you.

**Pull request merged**
