### PR TITLE
bugfix/no-saves-on-steam-jul-2020

### LINKED ISSUE #6: no saves on steam version (Jul-2020 65786)
Using the latest file from Nexus the game loads just fine but no autosaves are happening.

**game version**

- Steam Jul-2020 65786

**mod version**

- 1.3.5 (?)
- https://www.nexusmods.com/subnautica/mods/237?tab=files&file_id=2091
- v1.3.5-237-1-3-5-1583061282.zip

I'm not familiar with the logs enough to spot any errors.

### PR DESCRIPTION
**Pull request by Bisa**
Hi, this ought to fix #6

Please note that in order for the project to build I updated the paths,
you will need to set your old hard coded paths with the environmental SUBNAUTICA_PATH

I've also included the dll, remove it if you build it yourself (which I suppose you do).

### CODE REVIEW

**Comment by Bisa** [comment]
Revisiting the build options I realized that building with Configuration Release results in a non-working .dll, I'll just pull this one back for now until I figure that one out.

**Comment by Bisa** [comment]
Crisis averted.
I panicked when the mod was not auto saving every 60 seconds - but this lead me to investigate the DEBUG options further and I realized there's some interesting injections going on with Harmony.

Building with Configuration=Release this time around and it works as intended, attached resulting .dll
(you probably still build your one any way)

**Comment by Bisa** [comment]
I spent some time adjusting the build process after introducing the SUBNAUTICA_PATH earlier, this to allow me to build/debug locally as well as making the change backwards compatible with how I suspect your build environment looks.

I made a new section to the readme in an attempt to make it easier for others like me to start out when they want to build from source.

(the included .dll was built using this updated process)

**Comment by DingoDjango** [comment]
I don't have the game installed nor do I have access to my desktop PC at the moment.

Can you confirm the latest pull request works? Is the dll Release built and OK to upload to Nexus?

**Comment by Bisa** [comment]
@DingoDjango - I ran some tests with the debug build which looked to be working, however - just to make sure I did some additional testing with the Release configuration and it's still broken. I'll have to go back to the drawing board.

Be right back! :)

**Comment by Bisa** [comment]
@DingoDjango - It took another round of debugging but I've fixed (and tested the Release-build .dll)
I've opened #8 instead, please disregard this one.

**Pull request closed without merging**
